
workdir: "/scratch/cgobet/snake_codon/" # Working directory to be defined by user 
homedir: "/home/cgobet/SNAKE_METHODS/codonDT_snakemake/" # Home directory to be defined by user 
#Species (Mouse, Yeast or Human)
species: Yeast # Species to be defined by user 
#URL for Ensembls sequence files for Mouse, Human and Yeast (S. cer.)  
Mouse:
  cds: "ftp://ftp.ensembl.org/pub/release-95/fasta/mus_musculus/cds/Mus_musculus.GRCm38.cds.all.fa.gz" 
  gtf: "ftp://ftp.ensembl.org/pub/release-95/gtf/mus_musculus/Mus_musculus.GRCm38.95.gtf.gz"
  genome: "ftp://ftp.ensembl.org/pub/release-95/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz"

Human:
  cds: "ftp://ftp.ensembl.org/pub/release-95/fasta/homo_sapiens/cds/Homo_sapiens.GRCh38.cds.all.fa.gz"
  gtf: "ftp://ftp.ensembl.org/pub/release-95/gtf/homo_sapiens/Homo_sapiens.GRCh38.95.gtf.gz"
  genome: "ftp://ftp.ensembl.org/pub/release-95/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"

Yeast:
  cds: "ftp://ftp.ensembl.org/pub/release-95/fasta/saccharomyces_cerevisiae/cds/Saccharomyces_cerevisiae.R64-1-1.cds.all.fa.gz"
  gtf: "ftp://ftp.ensembl.org/pub/release-95/gtf/saccharomyces_cerevisiae/Saccharomyces_cerevisiae.R64-1-1.95.gtf.gz"
  genome: "ftp://ftp.ensembl.org/pub/release-95/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz"
 
# path to sample spreadsheet (TSV format, columns: SAMPLES, Type, SRR)
samples: samples.tsv # to be defined by user
# the sequencing adapter
adapter: TGGAATTCTCGGGTGCCAAGG  # 3' adapter to trimm
# lower bound read size
L1: "26"
# upper bound read size
L2: "36"
# Strandness of the the library (pos_neg or neg_pos)
library: "pos_neg"
# Filter threshold for the minimum number of reads per gene
filter_1: "100"
# Filter threshold for the p-value. Dwell times with p-value smaller than the threshold are plotted.
filter_2: "0.05"
# position of the A site from the 5'end of the read (set to 5 or 6)
pos_A: "6"
